name: signwriting_flutter
description: "Flutter utilities for SignWriting formats, tokenizer and visualizer."
version: 1.0.2
repository: https://github.com/bipinkrish/signwriting-flutter
topics:
  - sign
  - signwriting

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  signwriting: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: SuttonSignWritingFill
      fonts:
        - asset: assets/SuttonSignWritingFill.ttf

    - family: SuttonSignWritingLine
      fonts:
        - asset: assets/SuttonSignWritingLine.ttf
